FROM python:3.7.6

RUN echo "mnist1.2 asdf"

WORKDIR /home/

RUN git clone https://github.com/lee-JunR/FashionMnist_api

WORKDIR /home/FashionMnist_api

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN python manage.py migrate

EXPOSE 5050

